### ISSUE TITLE
Not possible to add Songs from Libary to Playlist (Windows)

### ISSUE THREAD

**Issue by moszeed** [klnusbaum/UDJ-Desktop-Client#40]
Hi,
i cant add any Song from my Libary to the Playlist.
I`m on Windows XP.

Thx in Advance

**Comment by klnusbaum** [comment]
Can you please do the following:
1. Quit the player on windows
2. Open it back up and try to recreate the problem as quickly as possible.
3. Once the problem has been recreated, got to help->log
4. Paste the output of the Log here.

**Comment by klnusbaum** [comment]
This might actually be related to issue #41. I noticed on the server side you had two songs set as "currently playing" (which causes server errors). I've cleared them. Try adding your song now.

**Comment by moszeed** [comment]
Yes, now it works. Thx.

**Comment by moszeed** [comment]
Hi, the error is occurring again:

the log says following:

```
Explicitly setting server cas
Doing auth request
Got good auth reply
Setting player state to playing
Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>



Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>



Modding playlist failed
Active playlist mod failed with code 409
Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>
```

**Comment by klnusbaum** [comment]
I've cleared the playlist again, so you should be good to go. I'm going to try to push some code to the server this afternoon that will hopefully prevent this from happening anymore.

**Comment by klnusbaum** [comment]
Ok, I've pushed some new code to the server that should prevent this from happening anymore. I'm gonna close the issue for now, but feel free to reopen it if you have the problem again.

**Comment by moszeed** [comment]
Hi, first thanks.
But it happens again, we have hear 1 hour and then again, 
but this time we had still 2 Songs in the Playlist that played, and with this Songs playing
we couldn`t add Songs. The error feels a litte different.

```
Explicitly setting server cas
Doing auth request
Got good auth reply
Setting player state to playing
Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>



Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>



Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>



Modding playlist failed
Active playlist mod failed with code 409
Getting playlist failed
Playlist error: 500 error: <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Error 500</title>
  </head>

  <body>
    <p>  </p>
  </body>
</html>
```

**Comment by klnusbaum** [comment]
Alright, I'll look into it again today.

**Comment by klnusbaum** [comment]
By the way, thanks for being patient @moszeed . It's guinea pigs like you that help us go from unstable to being stable :)

**Comment by klnusbaum** [comment]
@moszeed  I've got a new build of the windows player. Would you mind sending me an e-mail at klnusbaum@bazaarsolutions.com . That way I'll have your e-mail address and I can shoot you an e-mail with the new build attached to it. I think it should help solve your problems.

**Comment by moszeed** [comment]
You got Mail! 

no problem, i am also a software developer and i know the pitfalls to a stable version ..

**Comment by klnusbaum** [comment]
@moszeed You been having any more problems? I take it since you've been quite things have been fixed :)

**Comment by klnusbaum** [comment]
@moszeed Reports that things seem to have settled down for him now. The windows client is far less likely now to set the current song quick enough that it exposes the race condition on the server. I'm going to close this issue.
