### ISSUE TITLE
When searching for a song, space bar toggles playback

### ISSUE THREAD

**Issue by klnusbaum** [klnusbaum/UDJ-Desktop-Client#59]
Steps to reproduce problem
1. Switch to library view
2. Start typing in the search box
3. Hit the space bar

What happens:
When you hit the space bar it toggles the playback.

What should happened:
Playback should be unaffected when entering information in the search box

**Comment by ClareCat** [comment]
I had this happen to me today =(

**Comment by murph** [comment]
https://github.com/UDJ/UDJ-Desktop-Client/pull/1
