### ISSUE TITLE
Error syncing library

### ISSUE THREAD

**Issue by dlip** [klnusbaum/UDJ-Desktop-Client#66]
After the login screen, I always get the error "Error syncing library. We'll try again next time you startup UDJ" on 2 separate ubuntu 12.04 boxes. Windows version seems fine though.

Doing auth request
Got good auth reply
Setting player state to playing
Starting playlist auto refresh
Starting particpants auto refresh
batching up sync
Found 0 songs which need deleting
Found 1 songs which need adding
Lib mod add JSON: [ { "album" : "US TOP20 Single Charts", "artist" : "Rihanna", "duration" : 220, "genre" : "Pop", "id" : "1", "title" : "Diamonds", "track" : 3 } ]
Lib mod delete JSON: [  ]
Lib mod payload: to_add=[ { "album" : "US TOP20 Single Charts", "artist" : "Rihanna", "duration" : 220, "genre" : "Pop", "id" : "1", "title" : "Diamonds", "track" : 3 } ]&to_delete=[  ]
Issued requestto_add=[ { "album" : "US TOP20 Single Charts", "artist" : "Rihanna", "duration" : 220, "genre" : "Pop", "id" : "1", "title" : "Diamonds", "track" : 3 } ]&to_delete=[  ]
Set reply propertiesto_add=[ { "album" : "US TOP20 Single Charts", "artist" : "Rihanna", "duration" : 220, "genre" : "Pop", "id" : "1", "title" : "Diamonds", "track" : 3 } ]&to_delete=[  ]
Player state set error 
Got bad lib mod
Got bad libmod 404
Bad lib mod message error: 
Getting playlist failed
Playlist error: 404 error: 
Participan get error 
Participan get error 
Getting playlist failed

**Comment by klnusbaum** [comment]
@dlip Do you see the Player set state error there? That means that you weren't able to actually set the player as active. Are you logging in as the same user that actually created the player?

**Comment by dlip** [comment]
After you log in once it greys out the username so you are locked to that account until you clear the settings folder doesn't it? I've also deleted the settings and tried again with the same result.

**Comment by klnusbaum** [comment]
@dlip which setting files did you delete? There are two import locations containing settings on linux.

**Comment by dlip** [comment]
~/.config/Bazaar\ Solutions
~/.local/share/data/Udj

full log of new try with different account
Doing auth request
Doing auth request
Doing auth request
Got good auth reply
DB file didn't exist, so creating it at: /home/dane/.local/share/data/Udj/playerdb
iTunes dir doesn't exist
Setting player state to playing
Starting playlist auto refresh
Starting particpants auto refresh
Player state set error 
got directory: 
Getting playlist failed
Playlist error: 404 error: 
File Ext Filter: (*.flac *.mp3 *.m4a *.wav *.ogg)
Participan get error 
Participan get error 
Getting playlist failed
Playlist error: 404 error: 
Participan get error 
Getting playlist failed
Playlist error: 404 error: 
Was able to start transaction
adding song with title: Artillery to database
Committing add transaction
batching up sync
Found 0 songs which need deleting
Found 1 songs which need adding
Lib mod add JSON: [ { "album" : "Vicious Delicious", "artist" : "Infected Mushroom", "duration" : 268, "genre" : "Electronic", "id" : "1", "title" : "Artillery", "track" : 2 } ]
Lib mod delete JSON: [  ]
Lib mod payload: to_add=[ { "album" : "Vicious Delicious", "artist" : "Infected Mushroom", "duration" : 268, "genre" : "Electronic", "id" : "1", "title" : "Artillery", "track" : 2 } ]&to_delete=[  ]
Issued requestto_add=[ { "album" : "Vicious Delicious", "artist" : "Infected Mushroom", "duration" : 268, "genre" : "Electronic", "id" : "1", "title" : "Artillery", "track" : 2 } ]&to_delete=[  ]
Set reply propertiesto_add=[ { "album" : "Vicious Delicious", "artist" : "Infected Mushroom", "duration" : 268, "genre" : "Electronic", "id" : "1", "title" : "Artillery", "track" : 2 } ]&to_delete=[  ]
Got bad lib mod
Got bad libmod 404
Bad lib mod message error: 
Participan get error 
Getting playlist failed
Playlist error: 404 error:

**Comment by klnusbaum** [comment]
Is it prompting you to create a new player? If not, then there are some settings files you missed. I'm not seeing any of the API class for creating a new player, as in it's still trying to modify stuff on an old player.

**Comment by klnusbaum** [comment]
Also, what's your UDJ user name?

**Comment by dlip** [comment]
Yeah, it comes up with the prompt for name and location. The account name is 77hzshared.

**Comment by klnusbaum** [comment]
What version of the client are you running?

**Comment by dlip** [comment]
0.6.2 from the ubuntu repository. I also ran a version built from master yesterday.

**Comment by klnusbaum** [comment]
I just checked our server logs and it looks like there are two players that are currently being polled: player-id 499 a.k.a. dane player and player-id 0. Player-id 0 doesn't exist. Do you have two UDJ processes running?

**Comment by dlip** [comment]
I might have had one running on the 2nd pc, I've shut it down and recreated one called dane again on the main pc.

**Comment by klnusbaum** [comment]
Hmmmm, player-id zero is still polling. that must not be you then. So why are you getting the 404s when syncing...

 I'm stumped at the moment :/ Let me think about it a little more. Do you see anything obvious in the source code yourself?

**Comment by klnusbaum** [comment]
@dlip I'm still not sure what's going on here. The latest version is 0.6.3. Have you tried building that from source?

**Comment by dlip** [comment]
Just tried the 0.6.3 ubuntu repository version on my home pc. When I try to add songs it says "Found 0 songs which need adding".

Doing auth request
Got good auth reply
DB file didn't exist, so creating it at: /home/dane/.local/share/data/Udj/playerdb
iTunes dir doesn't exist
Setting player state to playing
Starting playlist auto refresh
Starting particpants auto refresh
File Ext Filter: (*.flac *.mp3 *.m4a *.wav *.ogg)
Was able to start transaction
Committing add transaction
batching up sync
Found 0 songs which need deleting
Found 0 songs which need adding
